safe:        false
baseurl:     /
url: http://localhost:4000

name: Osvaldo JÃºnior
description: A passionate programmer living in Luanda
url: http://osvaldo.me
domain: osvaldo.me
commentlinks: true
twitter-username: mwanalezi
feedburnerurl: http://feeds.feedburner.com/mwanalezi
google-analytics-tracking-id: UA-43308679-1

source:      .
destination: ./_site
plugins:     ./_plugins
paginate_path: 'blog/page:num'

future:      true
lsi:         false
#pygments:    false
markdown:    kramdown
permalink:   /:title/
paginate: 5

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

excerpt_separator: "<!-- more -->"

sass:
    sass_dir: assets/_sass
    
# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 118441555665433735446
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: osvaldome
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-43308679-1

# Facebook Like
facebook_like: true

# Face comments
facebook_appid: 352067288256995

#Stackoverflow
stackoverflow_user: mwanalezi
stackoverflow_user_id: 452368